version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: logistika
    container_name: logistika-app
    restart: unless-stopped
    working_dir: /var/www/logistika-backend
    volumes:
      - ./:/var/www/logistika-backend
    networks:
      - logistika

  db:
    image: mysql:5.7
    container_name: logistika-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: logistika
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - logistika

  nginx:
    image: nginx:1.17-alpine
    container_name: logistika-nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/logistika-backend
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - logistika


networks:
  logistika:
    driver: bridge
